[package]
edition = "2021"
name = "pngme"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "1.8.1"
reqwest = { version = "0.11.8", features = ["blocking"] }
structopt = "0.3"
url = "2.2.2"
image = "0.23.14"
